/*
 * peri_PanelLEDTable.c
 *
 * Created on: 2014-3-27
 * Author: JH-LvSL
 */
#include <main.h>			//Declarations from DAVE3 Code Generation (includes SFR declaration)
#include <peri_PanelLEDButton.h>

const uint8_t PanelLEDTable[] =
{
		OPE_7SEG_LED_0,	//'0'  0
		OPE_7SEG_LED_1, //'1'  1
		OPE_7SEG_LED_2, //'2'  2
		OPE_7SEG_LED_3, //'3'  3
		OPE_7SEG_LED_4, //'4'  4
		OPE_7SEG_LED_5, //'5'  5
		OPE_7SEG_LED_6, //'6'  6
		OPE_7SEG_LED_7, //'7'  7
		OPE_7SEG_LED_8, //'8'  8
		OPE_7SEG_LED_9, //'9'  9
		OPE_7SEG_LED_A, //'A'  10
		OPE_7SEG_LED_B, //'B'  11
		OPE_7SEG_LED_C, //'C'  12
		OPE_7SEG_LED_D, //'D'  13
		OPE_7SEG_LED_E, //'E'  14
		OPE_7SEG_LED_F, //'F'  15
		OPE_7SEG_LED_G, //'G'  16
		OPE_7SEG_LED_H, //'H'  17
		OPE_7SEG_LED_I, //'I'  18
		OPE_7SEG_LED_J, //'J'  19
		OPE_7SEG_LED_K, //'K'  20
		OPE_7SEG_LED_L, //'L'  21
		OPE_7SEG_LED_M, //'M'  22
		OPE_7SEG_LED_N, //'N'  23
		OPE_7SEG_LED_O, //'O'  24
		OPE_7SEG_LED_P, //'P'  25
		OPE_7SEG_LED_Q, //'Q'  26
		OPE_7SEG_LED_R, //'R'  27
		OPE_7SEG_LED_S, //'S'  28
		OPE_7SEG_LED_T, //'T'  29
		OPE_7SEG_LED_U, //'U'  30
		OPE_7SEG_LED_V, //'V'  31
		OPE_7SEG_LED_W, //'W'  32
		OPE_7SEG_LED_X, //'X'  33
		OPE_7SEG_LED_Y, //'Y'  34
		OPE_7SEG_LED_Z, //'Z'  35
		OPE_7SEG_LED_NULL, //NULL 36
		OPE_7SEG_LED_SP, //'_'  37
		OPE_7SEG_LED_ZP //'-'  38
};
//故障显示添加
const uint8_t PanelAlmTable[][5] =
{
	/*No Alarm*/
	{OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL},
	/* 1 E.FO */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_F,OPE_7SEG_LED_O},
	/* 2 E.DOC */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_D,OPE_7SEG_LED_O,OPE_7SEG_LED_C},
	/* 3 E.POV */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_P,OPE_7SEG_LED_O,OPE_7SEG_LED_V},
	/* 4 E.COV */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_C,OPE_7SEG_LED_O,OPE_7SEG_LED_V},
	/* 5 E.PLV */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_P,OPE_7SEG_LED_L,OPE_7SEG_LED_V},
	/* 6 E.CLV */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_C,OPE_7SEG_LED_L,OPE_7SEG_LED_V},
	/* 7 E.DOL */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_D,OPE_7SEG_LED_O,OPE_7SEG_LED_L},
	/* 8 E.OS*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_O,OPE_7SEG_LED_S},
	/* 9 E.PD */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_P,OPE_7SEG_LED_D},
	/* 10 E.SD */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_S,OPE_7SEG_LED_D},
	/* 11 E.ES */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_E,OPE_7SEG_LED_S},
	/* 12 E.DOT */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_D,OPE_7SEG_LED_O,OPE_7SEG_LED_T},
	/* 13 E.EE */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_E,OPE_7SEG_LED_E},
	/* 14 E.EC*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_E,OPE_7SEG_LED_C},
	/* E.ECD E.BUS  15*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_B,OPE_7SEG_LED_U,OPE_7SEG_LED_S},
	/* E.ECE  16*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_E,OPE_7SEG_LED_C,OPE_7SEG_LED_E},
	/* E.ORL  17*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_O,OPE_7SEG_LED_R,OPE_7SEG_LED_L},
	/* E.PIFE 18*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_P,OPE_7SEG_LED_I,OPE_7SEG_LED_F,OPE_7SEG_LED_E},
	/* E.DCOF 19*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_D,OPE_7SEG_LED_C,OPE_7SEG_LED_O,OPE_7SEG_LED_F},
	/* E.AI1E 20*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_A,OPE_7SEG_LED_I,OPE_7SEG_LED_1,OPE_7SEG_LED_E},
	/* E.AI2E 21*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_A,OPE_7SEG_LED_I,OPE_7SEG_LED_2,OPE_7SEG_LED_E},
	/* E.AI3E 22*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_A,OPE_7SEG_LED_I,OPE_7SEG_LED_3,OPE_7SEG_LED_E},
	/* E.EPE  23*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_E,OPE_7SEG_LED_P,OPE_7SEG_LED_E},
	/* E.RLE  24*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_P,OPE_7SEG_LED_L,OPE_7SEG_LED_E},
	/* E.ECE1 25*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_E,OPE_7SEG_LED_C,OPE_7SEG_LED_E,OPE_7SEG_LED_1},
	/* E.ECE2 26*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_E,OPE_7SEG_LED_C,OPE_7SEG_LED_E,OPE_7SEG_LED_2},
	/* E.ECE3 27*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_E,OPE_7SEG_LED_C,OPE_7SEG_LED_E,OPE_7SEG_LED_3},
	/* E.EE1  28*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_E,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_NULL},
	/* E.EE2  29*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_E,OPE_7SEG_LED_E,OPE_7SEG_LED_2,OPE_7SEG_LED_NULL},
	/* E.EGE  30*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_E,OPE_7SEG_LED_G,OPE_7SEG_LED_E,OPE_7SEG_LED_NULL},
	/* E.POSE *///31
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_P,OPE_7SEG_LED_O,OPE_7SEG_LED_S,OPE_7SEG_LED_E},
	/* E.PHS *///32
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_P,OPE_7SEG_LED_H,OPE_7SEG_LED_S,OPE_7SEG_LED_NULL},
	/* E.MOC *///33
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_M,OPE_7SEG_LED_O,OPE_7SEG_LED_C},
	/* E.MOL  34*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_M,OPE_7SEG_LED_O,OPE_7SEG_LED_L},
	/* E.MOT  35*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_M,OPE_7SEG_LED_O,OPE_7SEG_LED_T},
	/* E.MC1  36*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_M,OPE_7SEG_LED_C,OPE_7SEG_LED_1},
	/* E.MC2  37*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_M,OPE_7SEG_LED_C,OPE_7SEG_LED_2},
	/* E.MDP  38*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_M,OPE_7SEG_LED_D,OPE_7SEG_LED_P},
	/* E.POT  39*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_P,OPE_7SEG_LED_O,OPE_7SEG_LED_T,OPE_7SEG_LED_NULL},
	/* E.NOT  40*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_N,OPE_7SEG_LED_O,OPE_7SEG_LED_T,OPE_7SEG_LED_NULL},
	/* E.OL   41*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_O,OPE_7SEG_LED_L,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL},
	/* 42 E.OT */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_O,OPE_7SEG_LED_T,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL},
	/* 43 E.POOS */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_P,OPE_7SEG_LED_O,OPE_7SEG_LED_O,OPE_7SEG_LED_S},
	/* E.SE16 44*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_6},
	/* E.SE10 45*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_0},
	/* E.SE11 46*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_1},
	/* E.SE12 47*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_2},
	/* E.SE13 48*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_3},
	/* E.SE14 49*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_4},
	/* E.SE15 50*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_5},
	/* E.SE17 51*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_7},
	/* 52 E.SE18 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_8},
	/* 53 E.SE19 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_1,OPE_7SEG_LED_9},
	/* 54 E.SE20 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_2,OPE_7SEG_LED_0},
	/* 55 E.SE21 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_S,OPE_7SEG_LED_E,OPE_7SEG_LED_2,OPE_7SEG_LED_1},
	/* 56 E.CUr1 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_C,OPE_7SEG_LED_U,OPE_7SEG_LED_R,OPE_7SEG_LED_1},
	/* 57 E.BrP1 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_B,OPE_7SEG_LED_R,OPE_7SEG_LED_P,OPE_7SEG_LED_1},
	/* 58 E.OLF1 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_O,OPE_7SEG_LED_L,OPE_7SEG_LED_F,OPE_7SEG_LED_1},
	/* 59 E.HOME */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_H,OPE_7SEG_LED_O,OPE_7SEG_LED_M,OPE_7SEG_LED_E},
	/* 60 E.ECAM 60*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_E,OPE_7SEG_LED_C,OPE_7SEG_LED_A,OPE_7SEG_LED_M},
	/* 61 A.ECAM 61*/
	{OPE_7SEG_LED_A&OPE_7SEG_LED_DP,OPE_7SEG_LED_E,OPE_7SEG_LED_C,OPE_7SEG_LED_A,OPE_7SEG_LED_M},
	/* 62 A.CREV 62*/
	{OPE_7SEG_LED_A&OPE_7SEG_LED_DP,OPE_7SEG_LED_C,OPE_7SEG_LED_R,OPE_7SEG_LED_E,OPE_7SEG_LED_V},

};

const uint8_t PanelAlmTable1[][5] =
{
	/*No Alarm*/
	{OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL,OPE_7SEG_LED_NULL},
	/* E.001   1*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_1},
	/* E.DOC  2*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_2},
	/* E.POV  3*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_3},
	/* E.COV  4*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_4},
	/* E.PLV  5*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_5},
	/* E.CLV  6*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_6},
	/* E.DOL  7*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_7},
	/* E.OS   8*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_8},
	/* E.PD   9*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_0,OPE_7SEG_LED_9},
	/* E.SD   10*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_0},
	/* E.ES   11*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_1},
	/* E.DOT  12*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_2},
	/* E.EE   13*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_3},
	/* E.EC   14*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_4},
	/* E.ECD E.BUS  15*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_5},
	/* E.ECE  16*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_6},
	/* E.ORL  17*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_7},
	/* E.PIFE 18*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_8},
	/* E.DCOF 19*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_9},
	/* E.AI1E 20*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_1,OPE_7SEG_LED_0},
	/* E.AI2E 21*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_1},
	/* E.AI3E 22*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_2},
	/* E.EPE  23*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_3},
	/* E.RLE  24*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_4},
	/* E.ECE1 25*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_5},
	/* E.ECE2 26*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_6},
	/* E.ECE3 27*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_7},
	/* E.EE1  28*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_8},
	/* E.EE2  29*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_2,OPE_7SEG_LED_9},
	/* E.EGE  30*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_0},
	/* E.POSE 31*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_1},
	/* E.PHS  32*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_2},
	/* E.MOC  33*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_3},
	/* E.MOL  34*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_4},
	/* E.MOT  35*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_5},
	/* E.MC1  36*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_6},
	/* E.MC2  37*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_7},
	/* E.MDP  38*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_8},
	/* E.POT  39*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_3,OPE_7SEG_LED_9},
	/* E.NOT  40*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_0},
	/* E.OL   41*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_1},
	/* E.OT   42*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_2},
	/* E.POOS 43*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_3},
	/* E.SE16 44*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_4},
	/* E.SE10 45*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_5},
	/* E.SE11 46*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_6},
	/* E.SE12 47*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_7},
	/* E.SE13 48*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_8},
	/* E.SE14 49*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_4,OPE_7SEG_LED_9},
	/* E.SE15 50*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_0},
	/* E.SE17 51*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_1},
	/* E.SE18 52*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_2},
	/* E.SE19 53*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_3},
	/* E.SE20 54*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_4},
	/* E.SE21 55*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_5},
	/* 56 E.CUr1 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_6},
	/* 57 E.BrP1 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_7},
	/* 58 E.OLF1 */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_8},
	/* 59 E.HOME */
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_5,OPE_7SEG_LED_9},
	/* 60 E.ECAM 60*/
	{OPE_7SEG_LED_E&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_6,OPE_7SEG_LED_0},
	/* A.ECAM 61*/
	{OPE_7SEG_LED_A&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_6,OPE_7SEG_LED_1},
	/* A.CREV 62*/
	{OPE_7SEG_LED_A&OPE_7SEG_LED_DP,OPE_7SEG_LED_NULL,OPE_7SEG_LED_0,OPE_7SEG_LED_6,OPE_7SEG_LED_2},

};

const uint8_t PanelDataStsTable[][5] =
{
		/*Saved*/
		{OPE_7SEG_LED_S,OPE_7SEG_LED_A,OPE_7SEG_LED_V,OPE_7SEG_LED_E,OPE_7SEG_LED_D},
		/*Not Changed For Servo-On*/
		{OPE_7SEG_LED_S,OPE_7SEG_LED_V,OPE_7SEG_LED_ZP,OPE_7SEG_LED_O,OPE_7SEG_LED_N},
		/*Changed Available After Power Reset*/
		{OPE_7SEG_LED_P,OPE_7SEG_LED_O,OPE_7SEG_LED_ZP,OPE_7SEG_LED_O,OPE_7SEG_LED_N},
		/*Only Read*/
		{OPE_7SEG_LED_R,OPE_7SEG_LED_ZP,OPE_7SEG_LED_O,OPE_7SEG_LED_L,OPE_7SEG_LED_Y}
};

const uint8_t  FuncTable[][5] =
{
		/*-JOG-*/
		{OPE_7SEG_LED_NULL,OPE_7SEG_LED_J,OPE_7SEG_LED_O,OPE_7SEG_LED_G,OPE_7SEG_LED_NULL},
		/*SAVE*/
		{OPE_7SEG_LED_NULL,OPE_7SEG_LED_S,OPE_7SEG_LED_A,OPE_7SEG_LED_V,OPE_7SEG_LED_E},
		/*-AT1-*/
		{OPE_7SEG_LED_ZP,OPE_7SEG_LED_A,OPE_7SEG_LED_T,OPE_7SEG_LED_1,OPE_7SEG_LED_ZP},
		/*-AT2-*/
		{OPE_7SEG_LED_ZP,OPE_7SEG_LED_A,OPE_7SEG_LED_T,OPE_7SEG_LED_2,OPE_7SEG_LED_ZP}
};
